---
abstract: 'bootstrap Rose::DB::Object and Rose::HTML::Form classes'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rose-DBx-Garden
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  File::Basename: '0'
  File::Slurp::Tiny: '0'
  Path::Class: '0'
  Rose::DB::Object: '0'
  Rose::DBx::TestDB: '0'
  Rose::HTML::Objects: '0'
  Rose::HTMLx::Form::Field::Autocomplete: '0'
  Rose::HTMLx::Form::Field::Boolean: '0.01'
  Rose::HTMLx::Form::Field::Serial: '0'
  Test::More: '0'
  perl: '5.008003'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-DBx-Garden
  homepage: https://github.com/karpet/rose-dbx-garden
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/rose-dbx-garden
version: '0.192'
