--- #YAML:1.0
name:                Rose-DBx-Garden
version:             0.11
abstract:            bootstrap Rose::DB::Object and Rose::HTML::Form classes
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dump:                    0
    File::Basename:                0
    File::Slurp:                   0
    Path::Class:                   0
    Rose::DB::Object:              0
    Rose::DBx::TestDB:             0
    Rose::HTML::Objects:           0
    Rose::HTMLx::Form::Field::Autocomplete: 0
    Rose::HTMLx::Form::Field::Boolean: 0.01
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
